#ifndef FILEPROCESSINGTOOL_GLOBAL_H
#define FILEPROCESSINGTOOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILEPROCESSINGTOOL_LIBRARY)
#  define FILEPROCESSINGTOOL_EXPORT Q_DECL_EXPORT
#else
#  define FILEPROCESSINGTOOL_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEPROCESSINGTOOL_GLOBAL_H
