#ifndef SETTINGSEXTENSION_GLOBAL_H
#define SETTINGSEXTENSION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SETTINGSEXTENSION_LIBRARY)
#  define SETTINGSEXTENSION_EXPORT Q_DECL_EXPORT
#else
#  define SETTINGSEXTENSION_EXPORT Q_DECL_IMPORT
#endif

#endif // SETTINGSEXTENSION_GLOBAL_H
