#ifndef MEDICALIMAGEBROWSER_GLOBAL_H
#define MEDICALIMAGEBROWSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MEDICALIMAGEBROWSER_LIBRARY)
#  define MEDICALIMAGEBROWSER_EXPORT Q_DECL_EXPORT
#else
#  define MEDICALIMAGEBROWSER_EXPORT Q_DECL_IMPORT
#endif

#endif // MEDICALIMAGEBROWSER_GLOBAL_H
